version: '3'
services:
  db:
    image: postgres:11
    restart: on-failure:3
    container_name: blog_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  worker:
    stdin_open: true
    container_name: blog_worker
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
    ports:
      - 3030:3000
    command: npm run start:dev
